name: Danger Review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [ checks_requested ]
  schedule:
    - cron: '15 1 * * 2'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  scan:
    name: Danger
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Generate secret files
      if: github.event_name == 'pull_request'
      run: |
        echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
        echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

    - name: Setup Detekt
      uses: peter-murray/setup-detekt@26449609a63e843a5b9bad8a4b63ef0ee717f7a5 # v3.0.0

    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt-cli --parallel -i ${{ github.workspace }} -c ${{ github.workspace }}/config/detekt/detekt.yml \
        -r xml:${{ github.workspace }}/detekt.xml \
        -r sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Upload Detekt SARIF report
      uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@708024e6c902387ab41de36e1669e43b5ee7085e # v1.283.0
      with:
        bundler-cache: true

    - name: Run Rubocop
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Rubocop SARIF report
      uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
      with:
        sarif_file: ${{ github.workspace }}/rubocop.sarif
        checkout_path: ${{ github.workspace }}

    - name: Run Danger
      if: github.event_name == 'pull_request'
      uses: MeilCli/danger-action@d3bf36a2cd9af4990ba7727804f2b882451251da # v6.0.46
      with:
        plugins_file: "Gemfile"
        danger_file: "Dangerfile"
        danger_id: "danger-pr"
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_TOKEN }}
