name: Danger Review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 1 * * 2'
  workflow_dispatch:

permissions:
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  scan:
    name: Danger
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/r0adkll/danger-kotlin:v2.1.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Generate secret files
      if: github.event_name == 'pull_request'
      run: |
        echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
        echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

    - name: Setup Detekt
      uses: peter-murray/setup-detekt@26449609a63e843a5b9bad8a4b63ef0ee717f7a5 # v3.0.0

    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt-cli --parallel -i ${{ github.workspace }} -c ${{ github.workspace }}/config/detekt/detekt.yml \
        -r xml:${{ github.workspace }}/detekt.xml \
        -r sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Upload Detekt SARIF report
      uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v4.31.2
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}

    - name: Run Danger
      if: github.event_name == 'pull_request'
      run: danger-kotlin ci
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_TOKEN }}
