name: Danger Review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 1 * * 2'
  workflow_dispatch:

permissions:
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  scan:
    name: Danger
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/r0adkll/danger-kotlin:2.1.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Make directory safe
      run: git config --global --add safe.directory ${{ github.workspace }}

    - name: Setup Detekt
      uses: peter-murray/setup-detekt@26449609a63e843a5b9bad8a4b63ef0ee717f7a5 # v3.0.0

    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt-cli --parallel -i . -c config/detekt/detekt.yml -r xml:detekt.xml -r sarif:detekt.sarif.json

    - name: Upload Detekt SARIF report
      uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v4.31.2
      with:
        sarif_file: detekt.sarif.json
        checkout_path: .

    - name: Run Danger
      if: github.event_name == 'pull_request'
      run: danger-kotlin ci
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_TOKEN }}
