name: Danger Review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 1 * * 2'
  workflow_dispatch:

permissions:
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  scan:
    name: Danger
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Generate secret files
      if: github.event_name == 'pull_request'
      run: |
        echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties
        echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d > ${{ github.workspace }}/app/google-services.json

    - name: Setup Detekt
      uses: peter-murray/setup-detekt@26449609a63e843a5b9bad8a4b63ef0ee717f7a5 # v3.0.0

    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt-cli --parallel -i ${{ github.workspace }} -c ${{ github.workspace }}/config/detekt/detekt.yml \
        -r xml:${{ github.workspace }}/detekt.xml \
        -r sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Upload Detekt SARIF report
      uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@8a836efbcebe5de0fe86b48a775b7a31b5c70c93 # v1.277.0
      with:
        bundler-cache: true

    - name: Run Rubocop
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Rubocop SARIF report
      uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      with:
        sarif_file: ${{ github.workspace }}/rubocop.sarif
        checkout_path: ${{ github.workspace }}

    - name: Run Danger
      if: github.event_name == 'pull_request'
      uses: MeilCli/danger-action@22054113d79d0fe9b318e4a2b3dab7ad1ff68c30 # v6.0.43
      with:
        plugins_file: "Gemfile"
        danger_file: "Dangerfile"
        danger_id: "danger-pr"
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_TOKEN }}
