name: Pitest Mutation Testing

on:
  push:
    branches: [ "main" ]

jobs:
  pitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'IAN'
          - 'IAN/enums'
          - 'IAN/grid'
          - 'IAN/listener'
          - 'IAN/packets'
          - 'IAN/udp'
          - 'IAN/util'
          - 'IAN/vesseldata'
          - 'IAN/world'
    permissions:
      contents: read
      checks: write
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Restore Pitest history file
        uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ github.workspace }}/${{ matrix.path }}/build/pitHistory.txt
          key: pitest-history:${{ matrix.path }}

      - name: Generate secret files
        run: |
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 -d > ${{ github.workspace }}/keystore.properties

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: .tool-versions
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Determine Gradle module
        id: get-module
        uses: mad9000/actions-find-and-replace-string@bce4d50390d08b67e1822bd72fb54b3cf11b0ce9 # 5
        with:
          source: ${{ matrix.path }}
          find: '/'
          replace: ':'

      - name: Run Pitest
        run: ./gradlew :${{ steps.get-module.outputs.value }}:pitest

      - name: Check for any mutations
        id: mutations-check
        uses: thebinaryfelix/check-file-existence-action@b448944daf6428c03faa9b1974bcceb03408270d # 1.0.1
        with:
          files: ${{ github.workspace }}/${{ matrix.path }}/build/reports/pitest/mutations.xml

      - name: Upload Pitest report
        if: steps.mutations-check.outputs.exists == 'true'
        uses: Bonajo/pitest-report-action@e8b993da7e324031001987a0fea6a459c95d33e1 # v1.0.1
        with:
          name: Pitest Report (${{ matrix.path }})
          file: ${{ github.workspace }}/${{ matrix.path }}/build/reports/pitest/mutations.xml
          annotation-types: ALL

      - name: Cache Pitest history file
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ github.workspace }}/${{ matrix.path }}/build/pitHistory.txt
          key: pitest-history:${{ matrix.path }}-${{ hashFiles('**/build/pitHistory.txt') }}
